# -*- coding: utf-8 -*-
"""assignment4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bb5B8V5FTKJlo_u3sn8Zf60q3JTYhxDl
"""

#program to check prime or not

n=int(input("Enter number: "))

def prime(n):
    if n>1:
        
        for i in range(2,int(n/2)+1):
            if n%i==0:
                return("Not prime")
                break
        return("Prime")
    else:
        print("Prime ")
 
 
print(prime(n))